 let  data = [
    {
        id:1,
        group: 1,
        fullName: 'Иванов',
        object_1:['x','v','x','v','x','v','x','v','v','x','v'],
        object_2:['x','v','x','v','x','v','x','v','v','x','v'],
        object_3:['x','v','x','v','x','v','x','v','v','x','v'],
    },
    {
        id:2,
        group: 1,
        fullName: 'Петров',
        object_1:['x','x','x','x','x','v','v','v','v','v','v'],
        object_2:['v','v','v','v','v','v','v','v','v','v','v'],
        object_3:['v','v','v','v','v','v','x','x','x','x','x'],
    },
    {
        id:3,
        group: 1,
        fullName: 'Сидоров',
        object_1:['v','x','v','x','v','v','v','v','v','v','x'],
        object_2:['x','v','x','v','v','v','x','v','v','v','v'],
        object_3:['v','v','v','v','v','v','x','x','v','v','v'],
    },
    {
        id:4,
        group: 2,
        fullName: 'Сидорчуков',
        object_1:['x','v','v','x','v','v','x','x','v','v','x'],
        object_2:['x','v','v','v','v','v','x','x','v','v','v'],
        object_3:['x','v','v','v','v','v','x','x','v','v','v'],
    },
    {
        id:5,
        group: 2,
        fullName: 'Лапатин',
        object_1:['x','x','v','x','v','v','x','x','v','v','x'],
        object_2:['x','x','v','v','v','v','x','x','v','v','v'],
        object_3:['x','x','v','v','v','v','x','x','v','v','v'],
    },
    {
        id:6,
        group: 2,
        fullName: 'Ветров',
        object_1:['x','v','v','x','x','v','v','x','v','v','x'],
        object_2:['x','v','v','v','x','v','v','x','v','v','v'],
        object_3:['x','v','v','v','x','v','v','x','v','v','v'],
    },
    {
        id:7,
        group: 3,
        fullName: 'Дубинин',
        object_1:['v','v','v','v','v','v','v','x','v','v','x'],
        object_2:['v','v','v','v','v','v','v','v','v','v','x'],
        object_3:['v','v','v','v','v','v','x','x','v','v','x'],
    },
    {
        id:8,
        group: 3,
        fullName: 'Сидоренко',
        object_1:['x','x','x','x','v','v','x','x','v','v','x'],
        object_2:['x','x','x','x','v','v','x','x','v','v','v'],
        object_3:['x','x','x','x','v','v','x','x','v','v','v'],
    },
    {
        id:9,
        group: 3,
        fullName: 'Карпов',
        object_1:['v','v','v','v','v','v','v','v','v','v','x'],
        object_2:['v','v','v','v','v','v','v','v','v','v','v'],
        object_3:['v','v','v','v','v','v','v','v','v','v','v'],
    },
    {}
 ]
   